# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careersummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('best_finish', models.TextField()),
                ('speed', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('success', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('consistency', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('seasons', models.IntegerField()),
                ('qualifying', models.IntegerField()),
                ('finals', models.IntegerField()),
                ('stages', models.IntegerField()),
            ],
            options={
                'db_table': 'careersummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('category', models.TextField()),
                ('season', models.IntegerField()),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courseresult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('finish_point', models.IntegerField()),
                ('completed', models.BooleanField()),
            ],
            options={
                'db_table': 'courseresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('ninja_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ninja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('obstacle_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'obstacle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obstacleresult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('transition', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('duration', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('completed', models.BooleanField()),
            ],
            options={
                'db_table': 'obstacleresult',
                'managed': False,
            },
        ),
    ]
